### ISSUE TITLE
APEC interface for SPEX

### ISSUE THREAD

**Issue by LydiaStofanova** [spex-xray/pyspextools#1]
Hi Jelle, so I noticed that if the interface for APEC is used, the abundances in SPEX when you call _abundance show_, show the default value in SPEX and not the abundance that was chosen in the python interface for APEC. Is there a way how to change the ionization balance as well?

**Comment by jdeplaa** [comment]
Hi Lydia, thanks for your question. Since the APEC model is calculated outside SPEX using the ``user`` model, the regular SPEX settings, like the abundance, do not apply to APEC. In the ``user`` model, SPEX only sends the fit parameters and the energy grid to the python program (``apec.py``) and gets the APEC spectrum back. Any settings to the APEC model should therefore be done in the python program ``apec.py``.

If you look at line 89 of ``apec.py``, you see a line saying ``data.set_abundset("AG89")``. This is the APEC or PYATOMDB way of setting the solar abundance values (in this case Anders and Grevesse 1989). For the options that you have here, please see [the PYATOMDB documentation](https://atomdb.readthedocs.io/en/master/atomdb.html#pyatomdb.atomdb.get_abundance). The same holds for the ionisation balance. PYATOMDB has options to change the ionisation balance, but not using a short command. See [the PYATOMDB documentation](https://atomdb.readthedocs.io/en/master/index.html).
