### ISSUE TITLE
Issues with User model

### ISSUE THREAD

**Issue by ethlau** [spex-xray/pyspextools#2]
I tried to run the User model tutorial on https://spex-xray.github.io/pyspextools/tutorials/myusermodel.html, but I get the following after running
`usr=User()`

```
Error: Cannot read input filename from command line.
 Please only use this module in an executable.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyspextools/model/user.py", line 63, in __init__
    self.fprm = sys.argv[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c7510f5a0854>", line 1, in <module>
    usr = User()
  File "/usr/local/lib/python3.8/site-packages/pyspextools/model/user.py", line 67, in __init__
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
```

**Comment by jdeplaa** [comment]
Thanks for reporting this issue. I think the problem is that the user model is intended for use within the [SPEX program](https://doi.org/10.5281/zenodo.1924563).

The idea is that the input parameters for the model and the energy grid are defined in the SPEX program and then passed to the user model through a text file. The name of this text file is passed through the command line. Using this input, the model can be calculated and the output spectrum is passed back to SPEX where it can be fitted to data.

Looking at your error output, you are running the User model in an iPython session. However, this module expects that it is run as an executable like: `./myusermodel.sh input-01-01.prm`, so it can get the filename `input-01-01.prm` from the command line. The `sys.argv[1]` variable does not exist in your case and the call to `User()` fails.

You can find some examples about how to use the `user` model here: https://spex-xray.github.io/spex-help/threads/user/user.html

I see that the documentation is not very clear at this point. Please let me know if you have suggestions to improve it.

**Comment by myh-art** [comment]
Hi,
I have a issue like this: bash: com command not found... the system I use is centos 7,how can I deal with this issue?
Thank you for your answer

Mingyue

**Comment by jmao2014** [comment]
I am not sure whether I understand your issue. I guess that you encountered this error message when trying to call "spex" in the terminal? If so, please check out Section 1.1.2 of the following thread. User needs to set the SPEX90 environment variable and initialize $SPEX90/spexdist.sh before calling "spex" in the terminal. 

https://spex-xray.github.io/spex-help/getstarted/install.html


If the above does not match your issue, can you give a more detailed description of the issue?  Thanks. 

Junjie
